# Auto-generated CPT reference list for foot and ankle procedures
# Format: List of dicts with 'code', 'description', 'category'

CPT_REFERENCE = [
    {"code": "27687", "description": "Gastrocnemius recession (eg, Strayer procedure)", "category": "ACHILLES"},
    {"code": "28120", "description": "Partial excision (craterization, saucerization, sequestrectomy, or diaphysectomy) bone (eg, osteomyelitis or bossing); talus or calcaneus", "category": "ACHILLES"},
    {"code": "27650", "description": "Repair, primary, open or percutaneous, ruptured Achilles tendon", "category": "ACHILLES"},
    {"code": "27654", "description": "Repair, secondary, Achilles tendon, with or without graft", "category": "ACHILLES"},
    {"code": "27606", "description": "Tenotomy, percutaneous, Achilles tendon (separate procedure); general anesthesia", "category": "ACHILLES"},
    {"code": "11043", "description": "Debridement, muscle and/or fascia (includes epidermis, dermis, and subcutaneous tissue, if performed); first 20 sq cm or less", "category": "ANKLE"},
    {"code": "27620", "description": "Arthrotomy, ankle, with joint exploration, with or without biopsy, with or without removal of loose or foreign body", "category": "ANKLE"},
    {"code": "27637", "description": "Excision or curettage of bone cyst or benign tumor, tibia or fibula; with autograft (includes obtaining graft)", "category": "ANKLE"},
    {"code": "27640", "description": "Partial excision (craterization, saucerization, or diaphysectomy), bone (eg, osteomyelitis); tibia", "category": "ANKLE"},
    {"code": "27641", "description": "Partial excision (craterization, saucerization, or diaphysectomy), bone (eg, osteomyelitis); fibula", "category": "ANKLE"},
    {"code": "27659", "description": "Repair, flexor tendon, leg; secondary, with or without graft, each tendon", "category": "ANKLE"},
    {"code": "27675", "description": "Repair, dislocating peroneal tendons; without fibular osteotomy", "category": "ANKLE"},
    {"code": "27680", "description": "Tenolysis, flexor or extensor tendon, leg and/or ankle; single, each tendon", "category": "ANKLE"},
    {"code": "27686", "description": "Lengthening or shortening of tendon, leg or ankle; multiple tendons (through same incision), each", "category": "ANKLE"},
    {"code": "27695", "description": "Repair, primary, disrupted ligament, ankle; collateral", "category": "ANKLE"},
    {"code": "27698", "description": "Repair, secondary, disrupted ligament, ankle, collateral (eg, Watson-Jones procedure)", "category": "ANKLE"},
    {"code": "27702", "description": "Arthroplasty, ankle; with implant (total ankle)", "category": "ANKLE"},
    {"code": "27766", "description": "Open treatment of medial malleolus fracture, includes internal fixation, when performed", "category": "ANKLE"},
    {"code": "27769", "description": "Open treatment of posterior malleolus fracture, includes internal fixation, when performed", "category": "ANKLE"},
    {"code": "27792", "description": "Open treatment of distal fibular fracture (lateral malleolus), includes internal fixation, when performed", "category": "ANKLE"},
    {"code": "27814", "description": "Open treatment of bimalleolar ankle fracture (eg, lateral and medial malleoli, or lateral and posterior malleoli, or medial and posterior malleoli), includes internal fixation, when performed", "category": "ANKLE"},
    {"code": "27822", "description": "Open treatment of trimalleolar ankle fracture, includes internal fixation, when performed, medial and/or lateral malleolus; without fixation of posterior lip", "category": "ANKLE"},
    {"code": "27823", "description": "Open treatment of trimalleolar ankle fracture, includes internal fixation, when performed, medial and/or lateral malleolus; with fixation of posterior lip", "category": "ANKLE"},
    {"code": "27829", "description": "Open treatment of distal tibiofibular joint (syndesmosis) disruption, includes internal fixation, when performed", "category": "ANKLE"},
    {"code": "27870", "description": "Arthrodesis, ankle, open", "category": "ANKLE"},
    {"code": "28445", "description": "Open treatment of talus fracture, includes internal fixation, when performed", "category": "ANKLE"},
    {"code": "29897", "description": "Arthroscopy, ankle (tibiotalar and fibulotalar joints), surgical; debridement, limited", "category": "ARTHROSCOPY"},
    {"code": "29898", "description": "Arthroscopy, ankle (tibiotalar and fibulotalar joints), surgical; debridement, extensive", "category": "ARTHROSCOPY"},
    {"code": "29904", "description": "Arthroscopy, subtalar joint, surgical; with removal of loose body or foreign body", "category": "ARTHROSCOPY"},
    {"code": "29906", "description": "Arthroscopy, subtalar joint, surgical; with debridement", "category": "ARTHROSCOPY"},
    {"code": "27690", "description": "Transfer or transplant of single tendon (with muscle redirection or rerouting); superficial (eg, anterior tibial extensors into midfoot)", "category": "FOREFOOT"},
    {"code": "28080", "description": "Excision, interdigital (Morton) neuroma, single, each", "category": "FOREFOOT"},
    {"code": "28090", "description": "Excision of lesion, tendon, tendon sheath, or capsule (including synovectomy) (eg, cyst or ganglion); foot", "category": "FOREFOOT"},
    {"code": "28113", "description": "Ostectomy, complete excision; fifth metatarsal head", "category": "FOREFOOT"},
    {"code": "28114", "description": "Ostectomy, complete excision; all metatarsal heads, with partial proximal phalangectomy, excluding first metatarsal (eg, Clayton type procedure)", "category": "FOREFOOT"},
    {"code": "28122", "description": "Partial excision (craterization, saucerization, sequestrectomy, or diaphysectomy) bone (eg, osteomyelitis or bossing); tarsal or metatarsal bone, except talus or calcaneus", "category": "FOREFOOT"},
    {"code": "28124", "description": "Partial excision (craterization, saucerization, sequestrectomy, or diaphysectomy) bone (eg, osteomyelitis or bossing); phalanx of toe", "category": "FOREFOOT"},
    {"code": "28208", "description": "Repair, tendon, extensor, foot; primary or secondary, each tendon", "category": "FOREFOOT"},
    {"code": "28232", "description": "Tenotomy, open, tendon flexor; toe, single tendon (separate procedure)", "category": "FOREFOOT"},
    {"code": "28270", "description": "Capsulotomy; metatarsophalangeal joint, with or without tenorrhaphy, each joint (separate procedure)", "category": "FOREFOOT"},
    {"code": "28285", "description": "Correction, hammertoe (eg, interphalangeal fusion, partial or total phalangectomy)", "category": "FOREFOOT"},
    {"code": "28306", "description": "Osteotomy, with or without lengthening, shortening or angular correction, metatarsal; first metatarsal", "category": "FOREFOOT"},
    {"code": "28308", "description": "Osteotomy, with or without lengthening, shortening or angular correction, metatarsal; other than first metatarsal, each", "category": "FOREFOOT"},
    {"code": "28312", "description": "Osteotomy, shortening, angular or rotational correction; other phalanges, any toe", "category": "FOREFOOT"},
    {"code": "28313", "description": "Reconstruction, angular deformity of toe, soft tissue procedures only (eg, overlapping second toe, fifth toe, curly toes)", "category": "FOREFOOT"},
    {"code": "28315", "description": "Sesamoidectomy, first toe (separate procedure)", "category": "FOREFOOT"},
    {"code": "28485", "description": "Open treatment of metatarsal fracture, includes internal fixation, when performed, each", "category": "FOREFOOT"},
    {"code": "28645", "description": "Open treatment of metatarsophalangeal joint dislocation, includes internal fixation, when performed", "category": "FOREFOOT"},
    {"code": "28810", "description": "Amputation, metatarsal, with toe, single", "category": "FOREFOOT"},
    {"code": "28820", "description": "Amputation, toe; metatarsophalangeal joint", "category": "FOREFOOT"},
    {"code": "28825", "description": "Amputation, toe; interphalangeal joint", "category": "FOREFOOT"},
    {"code": "10121", "description": "Incision and removal of foreign body, subcutaneous tissues; complicated", "category": "GRAFT/MISC"},
    {"code": "11044", "description": "Debridement, bone (includes epidermis, dermis, subcutaneous tissue, muscle and/or fascia, if performed); first 20 sq cm or less", "category": "GRAFT/MISC"},
    {"code": "11981", "description": "Insertion, drug-delivery implant (ie, bioresorbable, biodegradable, non-biodegradable)", "category": "GRAFT/MISC"},
    {"code": "20525", "description": "Removal of foreign body in muscle or tendon sheath; deep or complicated", "category": "GRAFT/MISC"},
    {"code": "20900", "description": "Bone graft, any donor area; minor or small (eg, dowel or button)", "category": "GRAFT/MISC"},
    {"code": "20902", "description": "Bone graft, any donor area; major or large", "category": "GRAFT/MISC"},
    {"code": "20932", "description": "Allograft, includes templating, cutting, placement and internal fixation, when performed; osteoarticular, including articular surface and contiguous bone (List separately in addition to code for primary procedure)", "category": "GRAFT/MISC"},
    {"code": "20933", "description": "Allograft, includes templating, cutting, placement and internal fixation, when performed; hemicortical intercalary, partial (ie, hemicylindrical) (List separately in addition to code for primary procedure)", "category": "GRAFT/MISC"},
    {"code": "20934", "description": "Allograft, includes templating, cutting, placement and internal fixation, when performed; intercalary, complete (ie, cylindrical) (List separately in addition to code for primary procedure)", "category": "GRAFT/MISC"},
    {"code": "97605", "description": "Negative pressure wound therapy (eg, vacuum assisted drainage collection), utilizing durable medical equipment (DME), including topical application(s), wound assessment, and instruction(s) for ongoing care, per session; total wound(s) surface area less than or equal to 50 square centimeters", "category": "GRAFT/MISC"},
    {"code": "97606", "description": "Negative pressure wound therapy (eg, vacuum assisted drainage collection), utilizing durable medical equipment (DME), including topical application(s), wound assessment, and instruction(s) for ongoing care, per session; total wound(s) surface area greater than 50 square centimeters", "category": "GRAFT/MISC"},
    {"code": "28208", "description": "Repair, tendon, extensor, foot; primary or secondary, each tendon", "category": "HALLUX"},
    {"code": "28289", "description": "Hallux rigidus correction with cheilectomy, debridement and capsular release of the first metatarsophalangeal joint; without implant", "category": "HALLUX"},
    {"code": "28296", "description": "Correction, hallux valgus (bunionectomy), with sesamoidectomy, when performed; with distal metatarsal osteotomy, any method", "category": "HALLUX"},
    {"code": "28297", "description": "Correction, hallux valgus (bunionectomy), with sesamoidectomy, when performed; with first metatarsal and medial cuneiform joint arthrodesis, any method", "category": "HALLUX"},
    {"code": "28298", "description": "Correction, hallux valgus (bunionectomy), with sesamoidectomy, when performed; with proximal phalanx osteotomy, any method", "category": "HALLUX"},
    {"code": "28299", "description": "Correction, hallux valgus (bunionectomy), with sesamoidectomy, when performed; with double osteotomy, any method", "category": "HALLUX"},
    {"code": "28310", "description": "Osteotomy, shortening, angular or rotational correction; proximal phalanx, first toe (separate procedure)", "category": "HALLUX"},
    {"code": "28315", "description": "Sesamoidectomy, first toe (separate procedure)", "category": "HALLUX"},
    {"code": "28505", "description": "Open treatment of fracture, great toe, phalanx or phalanges, includes internal fixation, when performed", "category": "HALLUX"},
    {"code": "28750", "description": "Arthrodesis, great toe; metatarsophalangeal joint", "category": "HALLUX"},
    {"code": "28755", "description": "Arthrodesis, great toe; interphalangeal joint", "category": "HALLUX"},
    {"code": "27630", "description": "Excision of lesion of tendon sheath or capsule (eg, cyst or ganglion), leg and/or ankle", "category": "HINDFOOT"},
    {"code": "27659", "description": "Repair, flexor tendon, leg; secondary, with or without graft, each tendon", "category": "HINDFOOT"},
    {"code": "27680", "description": "Tenolysis, flexor or extensor tendon, leg and/or ankle; single, each tendon", "category": "HINDFOOT"},
    {"code": "27686", "description": "Lengthening or shortening of tendon, leg or ankle; multiple tendons (through same incision), each", "category": "HINDFOOT"},
    {"code": "27691", "description": "Transfer or transplant of single tendon (with muscle redirection or rerouting); deep (eg, anterior tibial or posterior tibial through interosseous space, flexor digitorum longus, flexor hallucis longus, or peroneal tendon to midfoot or hindfoot)", "category": "HINDFOOT"},
    {"code": "28035", "description": "Release, tarsal tunnel (posterior tibial nerve decompression)", "category": "HINDFOOT"},
    {"code": "28060", "description": "Fasciectomy, plantar fascia; partial (separate procedure)", "category": "HINDFOOT"},
    {"code": "28090", "description": "Excision of lesion, tendon, tendon sheath, or capsule (including synovectomy) (eg, cyst or ganglion); foot", "category": "HINDFOOT"},
    {"code": "28116", "description": "Ostectomy, excision of tarsal coalition", "category": "HINDFOOT"},
    {"code": "28120", "description": "Partial excision (craterization, saucerization, sequestrectomy, or diaphysectomy) bone (eg, osteomyelitis or bossing); talus or calcaneus", "category": "HINDFOOT"},
    {"code": "28122", "description": "Partial excision (craterization, saucerization, sequestrectomy, or diaphysectomy) bone (eg, osteomyelitis or bossing); tarsal or metatarsal bone, except talus or calcaneus", "category": "HINDFOOT"},
    {"code": "28238", "description": "Reconstruction (advancement), posterior tibial tendon with excision of accessory tarsal navicular bone (eg, Kidner type procedure)", "category": "HINDFOOT"},
    {"code": "28262", "description": "Capsulotomy, midfoot; extensive, including posterior talotibial capsulotomy and tendon(s) lengthening (eg, resistant clubfoot deformity)", "category": "HINDFOOT"},
    {"code": "28300", "description": "Osteotomy; calcaneus (eg, Dwyer or Chambers type procedure), with or without internal fixation", "category": "HINDFOOT"},
    {"code": "28304", "description": "Osteotomy, tarsal bones, other than calcaneus or talus", "category": "HINDFOOT"},
    {"code": "28415", "description": "Open treatment of calcaneal fracture, includes internal fixation, when performed", "category": "HINDFOOT"},
    {"code": "28445", "description": "Open treatment of talus fracture, includes internal fixation, when performed", "category": "HINDFOOT"},
    {"code": "28465", "description": "Open treatment of tarsal bone fracture (except talus and calcaneus), includes internal fixation, when performed, each", "category": "HINDFOOT"},
    {"code": "28555", "description": "Open treatment of tarsal bone dislocation, includes internal fixation, when performed", "category": "HINDFOOT"},
    {"code": "28715", "description": "Arthrodesis; triple", "category": "HINDFOOT"},
    {"code": "28725", "description": "Arthrodesis; subtalar", "category": "HINDFOOT"},
    {"code": "28730", "description": "Arthrodesis, midtarsal or tarsometatarsal, multiple or transverse", "category": "HINDFOOT"},
    {"code": "28740", "description": "Arthrodesis, midtarsal or tarsometatarsal, single joint", "category": "HINDFOOT"},
    {"code": "20680", "description": "Removal of implant; deep (eg, buried wire, pin, screw, metal band, nail, rod or plate)", "category": "IMPLANT"},
    {"code": "28090", "description": "Excision of lesion, tendon, tendon sheath, or capsule (including synovectomy) (eg, cyst or ganglion); foot", "category": "MIDFOOT"},
    {"code": "28262", "description": "Capsulotomy, midfoot; extensive, including posterior talotibial capsulotomy and tendon(s) lengthening (eg, resistant clubfoot deformity)", "category": "MIDFOOT"},
    {"code": "28306", "description": "Osteotomy, with or without lengthening, shortening or angular correction, metatarsal; first metatarsal", "category": "MIDFOOT"},
    {"code": "28615", "description": "Open treatment of tarsometatarsal joint dislocation, includes internal fixation, when performed", "category": "MIDFOOT"},
    {"code": "28735", "description": "Arthrodesis, midtarsal or tarsometatarsal, multiple or transverse; with osteotomy (eg, flatfoot correction)", "category": "MIDFOOT"},
    {"code": "28740", "description": "Arthrodesis, midtarsal or tarsometatarsal, single joint", "category": "MIDFOOT"},
]
